Repository ramsharma13/JQUERYLogic_-hacktoberfest, pull requests merged in 2023-10, with the labels that each got.

#1 Calculator.js
  Calculator.js
Labels: enhancement, good first issue, hacktoberfest-accepted

#2 Create CRUDOperation.js
  CRUDOperation.js
Labels: enhancement, good first issue, hacktoberfest-accepted

#3 Create HideShow.js
  HideShow.js
Labels: enhancement, good first issue, hacktoberfest-accepted

#10 Create Where_TO.js
  Where_TO.js
Labels: good first issue, hacktoberfest-accepted

#4 Create Popup.html
  Popup.html
Labels: good first issue, hacktoberfest-accepted

#9 Create Array_Iteration.js
  Array_Iteration.js
Labels: good first issue, hacktoberfest-accepted

#7 Create SwitchStatement.js
  SwitchStatement.js
Labels: good first issue, hacktoberfest-accepted

#6 Create JSONP.php
  JSONP.php
  Variable.js
Labels: good first issue, hacktoberfest-accepted

#8 Create GetMethod.js
  GetMethod.js
Labels: enhancement, good first issue, hacktoberfest-accepted

#5 Create Callbackfunction.js
  Callbackfunction.js
Labels: enhancement, good first issue, hacktoberfest-accepted

#11 Create Stopwatch.js
  Rintone.js
  Stopwatch.js
Labels: enhancement, good first issue, hacktoberfest-accepted

#13 Create CounterApp.js
  CounterApp.js
Labels: enhancement, good first issue, hacktoberfest-accepted

#14 Create Binary_tree.cs
  Binary_tree.cs
Labels: good first issue, hacktoberfest-accepted

#15 DropDown.js
  DropDown.js
Labels: enhancement, good first issue, hacktoberfest-accepted

#16 Drag.js
  Drag.js
Labels: good first issue, hacktoberfest-accepted

#17 SLice.js
  SLice.js
Labels: enhancement, good first issue, hacktoberfest-accepted

#19 Create RandomNumber.js
  RandomNumber.js
Labels: enhancement, good first issue, hacktoberfest-accepted

#18 BinarySearch.java
  BinarySearch.java
Labels: good first issue, hacktoberfest-accepted

#20 Fibonacci.js
  Fibonacci.js
Labels: enhancement, good first issue, hacktoberfest-accepted

#21 jQueryCheck.js
  jQueryCheck.js
Labels: good first issue, hacktoberfest-accepted

#22 CAPTCHAGEN.js
  CAPTCHAGEN.js
Labels: good first issue, hacktoberfest-accepted, hacktoberfest

#23 TicTacTOe.js
  TicTacTOe.js
Labels: good first issue, hacktoberfest-accepted, hacktoberfest
